/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jy_xinlangweibo_constant_Constants */

#ifndef _Included_com_jy_xinlangweibo_constant_Constants
#define _Included_com_jy_xinlangweibo_constant_Constants
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jy_xinlangweibo_constant_Constants
 * Method:    getKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jy_xinlangweibo_constant_Constants_getKey
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
